// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS


// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
// VCS coverage exclude_file
module ram_2x334(	// src/main/scala/chisel3/util/Queue.scala:73:91
  input          R0_addr,
                 R0_en,
                 R0_clk,
  output [333:0] R0_data,
  input          W0_addr,
                 W0_en,
                 W0_clk,
  input  [333:0] W0_data
);

  reg [333:0] Memory[0:1];	// src/main/scala/chisel3/util/Queue.scala:73:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Queue.scala:73:91
    if (W0_en & 1'h1)	// src/main/scala/chisel3/util/Queue.scala:73:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Queue.scala:73:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/chisel3/util/Queue.scala:73:91
    reg [351:0] _RANDOM_MEM;	// src/main/scala/chisel3/util/Queue.scala:73:91
    initial begin	// src/main/scala/chisel3/util/Queue.scala:73:91
      `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:73:91
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/chisel3/util/Queue.scala:73:91
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          for (logic [8:0] j = 9'h0; j < 9'h160; j += 9'h20) begin
            _RANDOM_MEM[j +: 32] = `RANDOM;	// src/main/scala/chisel3/util/Queue.scala:73:91
          end
          Memory[i[0]] = _RANDOM_MEM[333:0];	// src/main/scala/chisel3/util/Queue.scala:73:91
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 334'bx;	// src/main/scala/chisel3/util/Queue.scala:73:91
endmodule

module Queue2_TileLink_A_ChannelBase(	// src/main/scala/chisel3/util/Queue.scala:60:7
  input          clock,	// src/main/scala/chisel3/util/Queue.scala:60:7
                 reset,	// src/main/scala/chisel3/util/Queue.scala:60:7
  output         io_enq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input          io_enq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [2:0]   io_enq_bits_opcode,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_enq_bits_param,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [4:0]   io_enq_bits_size,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [5:0]   io_enq_bits_source,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [31:0]  io_enq_bits_address,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_enq_bits_mask,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [255:0] io_enq_bits_data,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [4:0]   io_enq_bits_user_rsvd,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [3:0]   io_enq_bits_user_instr_type,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [6:0]   io_enq_bits_user_cmd_intg,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_enq_bits_user_data_intg,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input          io_deq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output         io_deq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [2:0]   io_deq_bits_opcode,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [4:0]   io_deq_bits_size,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [5:0]   io_deq_bits_source,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [31:0]  io_deq_bits_address,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_deq_bits_mask,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [255:0] io_deq_bits_data	// src/main/scala/chisel3/util/Queue.scala:72:14
);

  wire [333:0] _ram_ext_R0_data;	// src/main/scala/chisel3/util/Queue.scala:73:91
  reg          wrap;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg          wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg          maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27
  wire         ptr_match = wrap == wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:77:33
  wire         empty = ptr_match & ~maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :77:33, :78:{25,28}
  wire         full = ptr_match & maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :77:33, :79:24
  wire         do_enq = ~full & io_enq_valid;	// src/main/scala/chisel3/util/Queue.scala:79:24, :103:19, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
    if (reset) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      wrap <= 1'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
      wrap_1 <= 1'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
    end
    else begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      automatic logic do_deq = io_deq_ready & ~empty;	// src/main/scala/chisel3/util/Queue.scala:78:25, :102:19, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      if (do_enq)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        wrap <= wrap - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (do_deq)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        wrap_1 <= wrap_1 - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (~(do_enq == do_deq))	// src/main/scala/chisel3/util/Queue.scala:76:27, :93:{15,27}, :94:16, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Queue.scala:76:27, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Queue.scala:60:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Queue.scala:60:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Queue.scala:60:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Queue.scala:60:7
        wrap = _RANDOM[/*Zero width*/ 1'b0][0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
        wrap_1 = _RANDOM[/*Zero width*/ 1'b0][1];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][2];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_2x334 ram_ext (	// src/main/scala/chisel3/util/Queue.scala:73:91
    .R0_addr (wrap_1),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (wrap),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    .W0_clk  (clock),
    .W0_data
      ({io_enq_bits_opcode,
        io_enq_bits_size,
        io_enq_bits_source,
        io_enq_bits_address,
        io_enq_bits_mask,
        io_enq_bits_data})	// src/main/scala/chisel3/util/Queue.scala:73:91
  );	// src/main/scala/chisel3/util/Queue.scala:73:91
  assign io_enq_ready = ~full;	// src/main/scala/chisel3/util/Queue.scala:60:7, :79:24, :103:19
  assign io_deq_valid = ~empty;	// src/main/scala/chisel3/util/Queue.scala:60:7, :78:25, :102:19
  assign io_deq_bits_opcode = _ram_ext_R0_data[333:331];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_size = _ram_ext_R0_data[330:326];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_source = _ram_ext_R0_data[325:320];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_address = _ram_ext_R0_data[319:288];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_mask = _ram_ext_R0_data[287:256];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_data = _ram_ext_R0_data[255:0];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
endmodule

module CoralNPURRArbiter(	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:52:7
  input          clock,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:52:7
                 reset,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:52:7
  output         io_in_0_ready,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input          io_in_0_valid,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input  [2:0]   io_in_0_bits_opcode,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
                 io_in_0_bits_param,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input  [4:0]   io_in_0_bits_size,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input  [5:0]   io_in_0_bits_source,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input          io_in_0_bits_sink,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input  [255:0] io_in_0_bits_data,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input  [6:0]   io_in_0_bits_user_rsp_intg,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
                 io_in_0_bits_user_data_intg,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input          io_in_0_bits_error,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  output         io_in_1_ready,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input          io_in_1_valid,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input  [2:0]   io_in_1_bits_opcode,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
                 io_in_1_bits_param,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input  [4:0]   io_in_1_bits_size,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input  [5:0]   io_in_1_bits_source,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input          io_in_1_bits_sink,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input  [255:0] io_in_1_bits_data,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input  [6:0]   io_in_1_bits_user_rsp_intg,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
                 io_in_1_bits_user_data_intg,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input          io_in_1_bits_error,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
                 io_out_ready,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  output         io_out_valid,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  output [2:0]   io_out_bits_opcode,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
                 io_out_bits_param,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  output [4:0]   io_out_bits_size,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  output [5:0]   io_out_bits_source,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  output         io_out_bits_sink,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  output [255:0] io_out_bits_data,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  output [6:0]   io_out_bits_user_rsp_intg,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
                 io_out_bits_user_data_intg,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  output         io_out_bits_error	// src/main/scala/chisel3/util/Arbiter.scala:52:14
);

  wire io_chosen_choice;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:47:26, :49:{24,33}
  wire io_out_valid_0 = io_chosen_choice ? io_in_1_valid : io_in_0_valid;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:47:26, :49:{24,33}, src/main/scala/chisel3/util/Arbiter.scala:55:16
  reg  ctrl_validMask_grantMask_lastGrant;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:34:31
  wire ctrl_validMask_1 = io_in_1_valid & ~ctrl_validMask_grantMask_lastGrant;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:34:31, :37:49, :38:76
  assign io_chosen_choice = ctrl_validMask_1 | ~io_in_0_valid;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:38:76, :45:41, :47:{26,35}, :49:{24,33}
  always @(posedge clock) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:52:7
    if (reset)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:52:7
      ctrl_validMask_grantMask_lastGrant <= 1'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:34:31, :52:7
    else if (io_out_ready & io_out_valid_0)	// src/main/scala/chisel3/util/Arbiter.scala:55:16, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      ctrl_validMask_grantMask_lastGrant <= io_chosen_choice;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:34:31, :47:26, :49:{24,33}
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:52:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:52:7
      `FIRRTL_BEFORE_INITIAL	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:52:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:52:7
      automatic logic [31:0] _RANDOM[0:0];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:52:7
      `ifdef INIT_RANDOM_PROLOG_	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:52:7
        `INIT_RANDOM_PROLOG_	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:52:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:52:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:52:7
        ctrl_validMask_grantMask_lastGrant = _RANDOM[/*Zero width*/ 1'b0][0];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:34:31, :52:7
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:52:7
      `FIRRTL_AFTER_INITIAL	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:52:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_0_ready = ~ctrl_validMask_1 & io_out_ready;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:28:78, :38:76, :52:7, src/main/scala/chisel3/util/Arbiter.scala:74:21
  assign io_in_1_ready =
    (~ctrl_validMask_grantMask_lastGrant | ~(ctrl_validMask_1 | io_in_0_valid))
    & io_out_ready;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:28:{68,78}, :34:31, :37:49, :38:76, :42:50, :52:7, src/main/scala/chisel3/util/Arbiter.scala:74:21
  assign io_out_valid = io_out_valid_0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:52:7, src/main/scala/chisel3/util/Arbiter.scala:55:16
  assign io_out_bits_opcode =
    io_chosen_choice ? io_in_1_bits_opcode : io_in_0_bits_opcode;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:47:26, :49:{24,33}, :52:7, src/main/scala/chisel3/util/Arbiter.scala:55:16
  assign io_out_bits_param = io_chosen_choice ? io_in_1_bits_param : io_in_0_bits_param;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:47:26, :49:{24,33}, :52:7, src/main/scala/chisel3/util/Arbiter.scala:55:16
  assign io_out_bits_size = io_chosen_choice ? io_in_1_bits_size : io_in_0_bits_size;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:47:26, :49:{24,33}, :52:7, src/main/scala/chisel3/util/Arbiter.scala:55:16
  assign io_out_bits_source =
    io_chosen_choice ? io_in_1_bits_source : io_in_0_bits_source;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:47:26, :49:{24,33}, :52:7, src/main/scala/chisel3/util/Arbiter.scala:55:16
  assign io_out_bits_sink = io_chosen_choice ? io_in_1_bits_sink : io_in_0_bits_sink;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:47:26, :49:{24,33}, :52:7, src/main/scala/chisel3/util/Arbiter.scala:55:16
  assign io_out_bits_data = io_chosen_choice ? io_in_1_bits_data : io_in_0_bits_data;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:47:26, :49:{24,33}, :52:7, src/main/scala/chisel3/util/Arbiter.scala:55:16
  assign io_out_bits_user_rsp_intg =
    io_chosen_choice ? io_in_1_bits_user_rsp_intg : io_in_0_bits_user_rsp_intg;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:47:26, :49:{24,33}, :52:7, src/main/scala/chisel3/util/Arbiter.scala:55:16
  assign io_out_bits_user_data_intg =
    io_chosen_choice ? io_in_1_bits_user_data_intg : io_in_0_bits_user_data_intg;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:47:26, :49:{24,33}, :52:7, src/main/scala/chisel3/util/Arbiter.scala:55:16
  assign io_out_bits_error = io_chosen_choice ? io_in_1_bits_error : io_in_0_bits_error;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/CoralNPUArbiter.scala:47:26, :49:{24,33}, :52:7, src/main/scala/chisel3/util/Arbiter.scala:55:16
endmodule

// VCS coverage exclude_file
module ram_2x289(	// src/main/scala/chisel3/util/Queue.scala:73:91
  input          R0_addr,
                 R0_en,
                 R0_clk,
  output [288:0] R0_data,
  input          W0_addr,
                 W0_en,
                 W0_clk,
  input  [288:0] W0_data
);

  reg [288:0] Memory[0:1];	// src/main/scala/chisel3/util/Queue.scala:73:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Queue.scala:73:91
    if (W0_en & 1'h1)	// src/main/scala/chisel3/util/Queue.scala:73:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Queue.scala:73:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/chisel3/util/Queue.scala:73:91
    reg [319:0] _RANDOM_MEM;	// src/main/scala/chisel3/util/Queue.scala:73:91
    initial begin	// src/main/scala/chisel3/util/Queue.scala:73:91
      `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:73:91
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/chisel3/util/Queue.scala:73:91
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          for (logic [8:0] j = 9'h0; j < 9'h140; j += 9'h20) begin
            _RANDOM_MEM[j +: 32] = `RANDOM;	// src/main/scala/chisel3/util/Queue.scala:73:91
          end
          Memory[i[0]] = _RANDOM_MEM[288:0];	// src/main/scala/chisel3/util/Queue.scala:73:91
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 289'bx;	// src/main/scala/chisel3/util/Queue.scala:73:91
endmodule

module Queue2_TileLink_D_ChannelBase(	// src/main/scala/chisel3/util/Queue.scala:60:7
  input          clock,	// src/main/scala/chisel3/util/Queue.scala:60:7
                 reset,	// src/main/scala/chisel3/util/Queue.scala:60:7
  output         io_enq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input          io_enq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [2:0]   io_enq_bits_opcode,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_enq_bits_param,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [4:0]   io_enq_bits_size,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [5:0]   io_enq_bits_source,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input          io_enq_bits_sink,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [255:0] io_enq_bits_data,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [6:0]   io_enq_bits_user_rsp_intg,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_enq_bits_user_data_intg,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input          io_enq_bits_error,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_deq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output         io_deq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [2:0]   io_deq_bits_opcode,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_deq_bits_param,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [4:0]   io_deq_bits_size,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [5:0]   io_deq_bits_source,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output         io_deq_bits_sink,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [255:0] io_deq_bits_data,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [6:0]   io_deq_bits_user_rsp_intg,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_deq_bits_user_data_intg,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output         io_deq_bits_error	// src/main/scala/chisel3/util/Queue.scala:72:14
);

  wire [288:0] _ram_ext_R0_data;	// src/main/scala/chisel3/util/Queue.scala:73:91
  reg          wrap;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg          wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg          maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27
  wire         ptr_match = wrap == wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:77:33
  wire         empty = ptr_match & ~maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :77:33, :78:{25,28}
  wire         full = ptr_match & maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :77:33, :79:24
  wire         do_enq = ~full & io_enq_valid;	// src/main/scala/chisel3/util/Queue.scala:79:24, :103:19, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
    if (reset) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      wrap <= 1'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
      wrap_1 <= 1'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
    end
    else begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      automatic logic do_deq = io_deq_ready & ~empty;	// src/main/scala/chisel3/util/Queue.scala:78:25, :102:19, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      if (do_enq)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        wrap <= wrap - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (do_deq)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        wrap_1 <= wrap_1 - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (~(do_enq == do_deq))	// src/main/scala/chisel3/util/Queue.scala:76:27, :93:{15,27}, :94:16, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Queue.scala:76:27, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Queue.scala:60:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Queue.scala:60:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Queue.scala:60:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Queue.scala:60:7
        wrap = _RANDOM[/*Zero width*/ 1'b0][0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
        wrap_1 = _RANDOM[/*Zero width*/ 1'b0][1];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][2];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_2x289 ram_ext (	// src/main/scala/chisel3/util/Queue.scala:73:91
    .R0_addr (wrap_1),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (wrap),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    .W0_clk  (clock),
    .W0_data
      ({io_enq_bits_opcode,
        io_enq_bits_param,
        io_enq_bits_size,
        io_enq_bits_source,
        io_enq_bits_sink,
        io_enq_bits_data,
        io_enq_bits_user_rsp_intg,
        io_enq_bits_user_data_intg,
        io_enq_bits_error})	// src/main/scala/chisel3/util/Queue.scala:73:91
  );	// src/main/scala/chisel3/util/Queue.scala:73:91
  assign io_enq_ready = ~full;	// src/main/scala/chisel3/util/Queue.scala:60:7, :79:24, :103:19
  assign io_deq_valid = ~empty;	// src/main/scala/chisel3/util/Queue.scala:60:7, :78:25, :102:19
  assign io_deq_bits_opcode = _ram_ext_R0_data[288:286];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_param = _ram_ext_R0_data[285:283];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_size = _ram_ext_R0_data[282:278];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_source = _ram_ext_R0_data[277:272];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_sink = _ram_ext_R0_data[271];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_data = _ram_ext_R0_data[270:15];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_user_rsp_intg = _ram_ext_R0_data[14:8];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_user_data_intg = _ram_ext_R0_data[7:1];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_error = _ram_ext_R0_data[0];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
endmodule

// VCS coverage exclude_file
module ram_size_2x5(	// src/main/scala/chisel3/util/Queue.scala:73:91
  input        R0_addr,
               R0_en,
               R0_clk,
  output [4:0] R0_data,
  input        W0_addr,
               W0_en,
               W0_clk,
  input  [4:0] W0_data
);

  reg [4:0] Memory[0:1];	// src/main/scala/chisel3/util/Queue.scala:73:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Queue.scala:73:91
    if (W0_en & 1'h1)	// src/main/scala/chisel3/util/Queue.scala:73:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Queue.scala:73:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/chisel3/util/Queue.scala:73:91
    reg [31:0] _RANDOM_MEM;	// src/main/scala/chisel3/util/Queue.scala:73:91
    initial begin	// src/main/scala/chisel3/util/Queue.scala:73:91
      `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:73:91
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/chisel3/util/Queue.scala:73:91
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/chisel3/util/Queue.scala:73:91
          Memory[i[0]] = _RANDOM_MEM[4:0];	// src/main/scala/chisel3/util/Queue.scala:73:91
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 5'bx;	// src/main/scala/chisel3/util/Queue.scala:73:91
endmodule

module Queue2_TxInfo(	// src/main/scala/chisel3/util/Queue.scala:60:7
  input        clock,	// src/main/scala/chisel3/util/Queue.scala:60:7
               reset,	// src/main/scala/chisel3/util/Queue.scala:60:7
  output       io_enq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input        io_enq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
               io_deq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output       io_deq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [4:0] io_deq_bits_size	// src/main/scala/chisel3/util/Queue.scala:72:14
);

  reg  wrap;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27
  wire ptr_match = wrap == wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:77:33
  wire empty = ptr_match & ~maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :77:33, :78:{25,28}
  wire full = ptr_match & maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :77:33, :79:24
  wire do_enq = ~full & io_enq_valid;	// src/main/scala/chisel3/util/Queue.scala:79:24, :103:19, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
    if (reset) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      wrap <= 1'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
      wrap_1 <= 1'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
    end
    else begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      automatic logic do_deq = io_deq_ready & ~empty;	// src/main/scala/chisel3/util/Queue.scala:78:25, :102:19, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      if (do_enq)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        wrap <= wrap - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (do_deq)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        wrap_1 <= wrap_1 - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (~(do_enq == do_deq))	// src/main/scala/chisel3/util/Queue.scala:76:27, :93:{15,27}, :94:16, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Queue.scala:76:27, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Queue.scala:60:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Queue.scala:60:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Queue.scala:60:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Queue.scala:60:7
        wrap = _RANDOM[/*Zero width*/ 1'b0][0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
        wrap_1 = _RANDOM[/*Zero width*/ 1'b0][1];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][2];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_size_2x5 ram_size_ext (	// src/main/scala/chisel3/util/Queue.scala:73:91
    .R0_addr (wrap_1),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (io_deq_bits_size),
    .W0_addr (wrap),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    .W0_clk  (clock),
    .W0_data (5'h5)	// src/main/scala/chisel3/util/Queue.scala:72:14
  );	// src/main/scala/chisel3/util/Queue.scala:73:91
  assign io_enq_ready = ~full;	// src/main/scala/chisel3/util/Queue.scala:60:7, :79:24, :103:19
  assign io_deq_valid = ~empty;	// src/main/scala/chisel3/util/Queue.scala:60:7, :78:25, :102:19
endmodule

module Queue1_AxiAddress(	// src/main/scala/chisel3/util/Queue.scala:60:7
  input         clock,	// src/main/scala/chisel3/util/Queue.scala:60:7
                reset,	// src/main/scala/chisel3/util/Queue.scala:60:7
  output        io_enq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input         io_enq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [31:0] io_enq_bits_addr,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [5:0]  io_enq_bits_id,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [2:0]  io_enq_bits_size,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input         io_deq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output        io_deq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [31:0] io_deq_bits_addr,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [2:0]  io_deq_bits_prot,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [5:0]  io_deq_bits_id,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [7:0]  io_deq_bits_len,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [2:0]  io_deq_bits_size,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [1:0]  io_deq_bits_burst	// src/main/scala/chisel3/util/Queue.scala:72:14
);

  reg [66:0] ram;	// src/main/scala/chisel3/util/Queue.scala:73:91
  reg        full;	// src/main/scala/chisel3/util/Queue.scala:76:27
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
    automatic logic do_enq;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    do_enq = ~full & io_enq_valid;	// src/main/scala/chisel3/util/Queue.scala:76:27, :103:19, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    if (reset)	// src/main/scala/chisel3/util/Queue.scala:60:7
      full <= 1'h0;	// src/main/scala/chisel3/util/Queue.scala:76:27
    else if (~(do_enq == (io_deq_ready & full)))	// src/main/scala/chisel3/util/Queue.scala:76:27, :93:{15,27}, :94:16, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      full <= do_enq;	// src/main/scala/chisel3/util/Queue.scala:76:27, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    if (do_enq)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      ram <= {io_enq_bits_addr, 3'h0, io_enq_bits_id, 8'h0, io_enq_bits_size, 15'h2000};	// src/main/scala/chisel3/util/Queue.scala:72:14, :73:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Queue.scala:60:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      automatic logic [31:0] _RANDOM[0:2];	// src/main/scala/chisel3/util/Queue.scala:60:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Queue.scala:60:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/chisel3/util/Queue.scala:60:7
        end	// src/main/scala/chisel3/util/Queue.scala:60:7
        full = _RANDOM[2'h0][0];	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
        ram = {_RANDOM[2'h0][31:1], _RANDOM[2'h1], _RANDOM[2'h2][3:0]};	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :76:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = ~full;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27, :103:19
  assign io_deq_valid = full;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
  assign io_deq_bits_addr = ram[66:35];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_prot = ram[34:32];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_id = ram[31:26];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_len = ram[25:18];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_size = ram[17:15];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_burst = ram[14:13];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
endmodule

module Queue1_AxiWriteData(	// src/main/scala/chisel3/util/Queue.scala:60:7
  input          clock,	// src/main/scala/chisel3/util/Queue.scala:60:7
                 reset,	// src/main/scala/chisel3/util/Queue.scala:60:7
  output         io_enq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input          io_enq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [255:0] io_enq_bits_data,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [31:0]  io_enq_bits_strb,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input          io_deq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output         io_deq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [255:0] io_deq_bits_data,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output         io_deq_bits_last,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [31:0]  io_deq_bits_strb	// src/main/scala/chisel3/util/Queue.scala:72:14
);

  reg [288:0] ram;	// src/main/scala/chisel3/util/Queue.scala:73:91
  reg         full;	// src/main/scala/chisel3/util/Queue.scala:76:27
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
    automatic logic do_enq;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    do_enq = ~full & io_enq_valid;	// src/main/scala/chisel3/util/Queue.scala:76:27, :103:19, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    if (reset)	// src/main/scala/chisel3/util/Queue.scala:60:7
      full <= 1'h0;	// src/main/scala/chisel3/util/Queue.scala:76:27
    else if (~(do_enq == (io_deq_ready & full)))	// src/main/scala/chisel3/util/Queue.scala:76:27, :93:{15,27}, :94:16, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      full <= do_enq;	// src/main/scala/chisel3/util/Queue.scala:76:27, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    if (do_enq)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      ram <= {io_enq_bits_data, 1'h1, io_enq_bits_strb};	// src/main/scala/chisel3/util/Queue.scala:73:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Queue.scala:60:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      automatic logic [31:0] _RANDOM[0:9];	// src/main/scala/chisel3/util/Queue.scala:60:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Queue.scala:60:7
        for (logic [3:0] i = 4'h0; i < 4'hA; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/chisel3/util/Queue.scala:60:7
        end	// src/main/scala/chisel3/util/Queue.scala:60:7
        full = _RANDOM[4'h0][0];	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
        ram =
          {_RANDOM[4'h0][31:1],
           _RANDOM[4'h1],
           _RANDOM[4'h2],
           _RANDOM[4'h3],
           _RANDOM[4'h4],
           _RANDOM[4'h5],
           _RANDOM[4'h6],
           _RANDOM[4'h7],
           _RANDOM[4'h8],
           _RANDOM[4'h9][1:0]};	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :76:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = ~full;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27, :103:19
  assign io_deq_valid = full;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
  assign io_deq_bits_data = ram[288:33];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_last = ram[32];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_strb = ram[31:0];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
endmodule

module SecdedEncoder_57(	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:75:7
  input  [56:0] io_data_i,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:85:14
  output [6:0]  io_ecc_o	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:85:14
);

  assign io_ecc_o =
    {^(io_data_i & 57'h1FBDDA769A46910),
     {^(io_data_i & 57'h1F7BB56D5525488),
      ^(io_data_i & 57'h1EF76CDB2C93244),
      ^(io_data_i & 57'h1DEEE3B8E388E22),
      ^(io_data_i & 57'h1BDE1F87E0781E1),
      ^(io_data_i & 57'h17C1FF801FF801F),
      ^(io_data_i & 57'h103FFF800007FFF)} ^ 6'h2A};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:56:{26,51}, :57:{26,51}, :58:{26,51}, :59:{26,51}, :60:{26,51}, :61:{26,51}, :62:{26,51}, :66:19, :75:7, :112:24
endmodule

module SecdedEncoder_256(	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:75:7
  input  [255:0] io_data_i,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:85:14
  output [6:0]   io_ecc_o	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:85:14
);

  assign io_ecc_o =
    {^{io_data_i[31:1] & 31'h4C282AC3, 1'h0},
     {^{io_data_i[29:2] & 28'hB731893, 2'h0},
      ^(io_data_i[31:0] & 32'hC2C1323B),
      ^(io_data_i[29:0] & 30'h31234ED1),
      ^{io_data_i[30:1] & 30'h209EC4D5, 1'h0},
      ^{io_data_i[31:4] & 28'hDEBA805, 4'h0},
      ^(io_data_i[29:0] & 30'h2606BD25)} ^ 6'h2A}
    ^ {^{io_data_i[63:33] & 31'h4C282AC3, 1'h0},
       {^{io_data_i[61:34] & 28'hB731893, 2'h0},
        ^(io_data_i[63:32] & 32'hC2C1323B),
        ^(io_data_i[61:32] & 30'h31234ED1),
        ^{io_data_i[62:33] & 30'h209EC4D5, 1'h0},
        ^{io_data_i[63:36] & 28'hDEBA805, 4'h0},
        ^(io_data_i[61:32] & 30'h2606BD25)} ^ 6'h2A}
    ^ {^{io_data_i[95:65] & 31'h4C282AC3, 1'h0},
       {^{io_data_i[93:66] & 28'hB731893, 2'h0},
        ^(io_data_i[95:64] & 32'hC2C1323B),
        ^(io_data_i[93:64] & 30'h31234ED1),
        ^{io_data_i[94:65] & 30'h209EC4D5, 1'h0},
        ^{io_data_i[95:68] & 28'hDEBA805, 4'h0},
        ^(io_data_i[93:64] & 30'h2606BD25)} ^ 6'h2A}
    ^ {^{io_data_i[127:97] & 31'h4C282AC3, 1'h0},
       {^{io_data_i[125:98] & 28'hB731893, 2'h0},
        ^(io_data_i[127:96] & 32'hC2C1323B),
        ^(io_data_i[125:96] & 30'h31234ED1),
        ^{io_data_i[126:97] & 30'h209EC4D5, 1'h0},
        ^{io_data_i[127:100] & 28'hDEBA805, 4'h0},
        ^(io_data_i[125:96] & 30'h2606BD25)} ^ 6'h2A}
    ^ {^{io_data_i[159:129] & 31'h4C282AC3, 1'h0},
       {^{io_data_i[157:130] & 28'hB731893, 2'h0},
        ^(io_data_i[159:128] & 32'hC2C1323B),
        ^(io_data_i[157:128] & 30'h31234ED1),
        ^{io_data_i[158:129] & 30'h209EC4D5, 1'h0},
        ^{io_data_i[159:132] & 28'hDEBA805, 4'h0},
        ^(io_data_i[157:128] & 30'h2606BD25)} ^ 6'h2A}
    ^ {^{io_data_i[191:161] & 31'h4C282AC3, 1'h0},
       {^{io_data_i[189:162] & 28'hB731893, 2'h0},
        ^(io_data_i[191:160] & 32'hC2C1323B),
        ^(io_data_i[189:160] & 30'h31234ED1),
        ^{io_data_i[190:161] & 30'h209EC4D5, 1'h0},
        ^{io_data_i[191:164] & 28'hDEBA805, 4'h0},
        ^(io_data_i[189:160] & 30'h2606BD25)} ^ 6'h2A}
    ^ {^{io_data_i[223:193] & 31'h4C282AC3, 1'h0},
       {^{io_data_i[221:194] & 28'hB731893, 2'h0},
        ^(io_data_i[223:192] & 32'hC2C1323B),
        ^(io_data_i[221:192] & 30'h31234ED1),
        ^{io_data_i[222:193] & 30'h209EC4D5, 1'h0},
        ^{io_data_i[223:196] & 28'hDEBA805, 4'h0},
        ^(io_data_i[221:192] & 30'h2606BD25)} ^ 6'h2A}
    ^ {^{io_data_i[255:225] & 31'h4C282AC3, 1'h0},
       {^{io_data_i[253:226] & 28'hB731893, 2'h0},
        ^(io_data_i[255:224] & 32'hC2C1323B),
        ^(io_data_i[253:224] & 30'h31234ED1),
        ^{io_data_i[254:225] & 30'h209EC4D5, 1'h0},
        ^{io_data_i[255:228] & 28'hDEBA805, 4'h0},
        ^(io_data_i[253:224] & 30'h2606BD25)} ^ 6'h2A};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:35:{26,45}, :36:{26,45}, :37:{26,45}, :38:{26,45}, :39:{26,45}, :40:{26,45}, :41:{26,45}, :45:19, :75:7, :103:{33,81,99}
endmodule

module ResponseIntegrityGen_32(	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:198:7
  input  [2:0]   io_d_i_opcode,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:200:14
                 io_d_i_param,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:200:14
  input  [4:0]   io_d_i_size,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:200:14
  input  [5:0]   io_d_i_source,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:200:14
  input          io_d_i_sink,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:200:14
  input  [255:0] io_d_i_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:200:14
  input  [6:0]   io_d_i_user_rsp_intg,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:200:14
                 io_d_i_user_data_intg,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:200:14
  input          io_d_i_error,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:200:14
  output [2:0]   io_d_o_opcode,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:200:14
                 io_d_o_param,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:200:14
  output [4:0]   io_d_o_size,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:200:14
  output [5:0]   io_d_o_source,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:200:14
  output         io_d_o_sink,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:200:14
  output [255:0] io_d_o_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:200:14
  output [6:0]   io_d_o_user_rsp_intg,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:200:14
                 io_d_o_user_data_intg,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:200:14
  output         io_d_o_error	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:200:14
);

  SecdedEncoder_57 rsp_encoder (	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:222:27
    .io_data_i ({48'h0, io_d_i_opcode, io_d_i_size, io_d_i_error}),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:215:12
    .io_ecc_o  (io_d_o_user_rsp_intg)
  );	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:222:27
  SecdedEncoder_256 data_encoder (	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:227:28
    .io_data_i (io_d_i_data),
    .io_ecc_o  (io_d_o_user_data_intg)
  );	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:227:28
  assign io_d_o_opcode = io_d_i_opcode;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:198:7
  assign io_d_o_param = io_d_i_param;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:198:7
  assign io_d_o_size = io_d_i_size;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:198:7
  assign io_d_o_source = io_d_i_source;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:198:7
  assign io_d_o_sink = io_d_i_sink;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:198:7
  assign io_d_o_data = io_d_i_data;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:198:7
  assign io_d_o_error = io_d_i_error;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulIntegrity.scala:198:7
endmodule

module TLUL2Axi(	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7
  input          clock,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7
                 reset,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7
  output         io_tl_a_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input          io_tl_a_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input  [2:0]   io_tl_a_bits_opcode,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
                 io_tl_a_bits_param,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input  [4:0]   io_tl_a_bits_size,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input  [5:0]   io_tl_a_bits_source,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input  [31:0]  io_tl_a_bits_address,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
                 io_tl_a_bits_mask,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input  [255:0] io_tl_a_bits_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input  [4:0]   io_tl_a_bits_user_rsvd,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input  [3:0]   io_tl_a_bits_user_instr_type,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input  [6:0]   io_tl_a_bits_user_cmd_intg,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
                 io_tl_a_bits_user_data_intg,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input          io_tl_d_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output         io_tl_d_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [2:0]   io_tl_d_bits_opcode,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
                 io_tl_d_bits_param,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [4:0]   io_tl_d_bits_size,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [5:0]   io_tl_d_bits_source,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output         io_tl_d_bits_sink,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [255:0] io_tl_d_bits_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [6:0]   io_tl_d_bits_user_rsp_intg,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
                 io_tl_d_bits_user_data_intg,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output         io_tl_d_bits_error,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input          io_axi_write_addr_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output         io_axi_write_addr_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [31:0]  io_axi_write_addr_bits_addr,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [2:0]   io_axi_write_addr_bits_prot,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [5:0]   io_axi_write_addr_bits_id,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [7:0]   io_axi_write_addr_bits_len,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [2:0]   io_axi_write_addr_bits_size,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [1:0]   io_axi_write_addr_bits_burst,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output         io_axi_write_addr_bits_lock,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [3:0]   io_axi_write_addr_bits_cache,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
                 io_axi_write_addr_bits_qos,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
                 io_axi_write_addr_bits_region,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input          io_axi_write_data_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output         io_axi_write_data_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [255:0] io_axi_write_data_bits_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output         io_axi_write_data_bits_last,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [31:0]  io_axi_write_data_bits_strb,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output         io_axi_write_resp_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input          io_axi_write_resp_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input  [5:0]   io_axi_write_resp_bits_id,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input  [1:0]   io_axi_write_resp_bits_resp,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input          io_axi_read_addr_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output         io_axi_read_addr_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [31:0]  io_axi_read_addr_bits_addr,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [2:0]   io_axi_read_addr_bits_prot,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [5:0]   io_axi_read_addr_bits_id,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [7:0]   io_axi_read_addr_bits_len,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [2:0]   io_axi_read_addr_bits_size,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [1:0]   io_axi_read_addr_bits_burst,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output         io_axi_read_addr_bits_lock,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output [3:0]   io_axi_read_addr_bits_cache,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
                 io_axi_read_addr_bits_qos,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
                 io_axi_read_addr_bits_region,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  output         io_axi_read_data_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input          io_axi_read_data_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input  [255:0] io_axi_read_data_bits_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input  [5:0]   io_axi_read_data_bits_id,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input  [1:0]   io_axi_read_data_bits_resp,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
  input          io_axi_read_data_bits_last	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:37:14
);

  wire [2:0]   _write_response_intg_io_d_o_opcode;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
  wire [2:0]   _write_response_intg_io_d_o_param;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
  wire [4:0]   _write_response_intg_io_d_o_size;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
  wire [5:0]   _write_response_intg_io_d_o_source;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
  wire         _write_response_intg_io_d_o_sink;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
  wire [255:0] _write_response_intg_io_d_o_data;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
  wire [6:0]   _write_response_intg_io_d_o_user_rsp_intg;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
  wire [6:0]   _write_response_intg_io_d_o_user_data_intg;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
  wire         _write_response_intg_io_d_o_error;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
  wire [2:0]   _read_response_intg_io_d_o_opcode;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
  wire [2:0]   _read_response_intg_io_d_o_param;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
  wire [4:0]   _read_response_intg_io_d_o_size;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
  wire [5:0]   _read_response_intg_io_d_o_source;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
  wire         _read_response_intg_io_d_o_sink;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
  wire [255:0] _read_response_intg_io_d_o_data;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
  wire [6:0]   _read_response_intg_io_d_o_user_rsp_intg;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
  wire [6:0]   _read_response_intg_io_d_o_user_data_intg;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
  wire         _read_response_intg_io_d_o_error;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
  wire         _w_q_io_enq_ready;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:98:19
  wire         _aw_q_io_enq_ready;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:85:20
  wire         _write_tx_info_q_io_enq_ready;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:75:31
  wire         _write_tx_info_q_io_deq_valid;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:75:31
  wire [4:0]   _write_tx_info_q_io_deq_bits_size;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:75:31
  wire         _read_tx_info_q_io_enq_ready;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:74:30
  wire         _read_tx_info_q_io_deq_valid;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:74:30
  wire [4:0]   _read_tx_info_q_io_deq_bits_size;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:74:30
  wire         _io_tl_d_q_io_enq_ready;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire         _d_channel_arb_io_in_0_ready;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
  wire         _d_channel_arb_io_in_1_ready;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
  wire         _d_channel_arb_io_out_valid;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
  wire [2:0]   _d_channel_arb_io_out_bits_opcode;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
  wire [2:0]   _d_channel_arb_io_out_bits_param;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
  wire [4:0]   _d_channel_arb_io_out_bits_size;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
  wire [5:0]   _d_channel_arb_io_out_bits_source;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
  wire         _d_channel_arb_io_out_bits_sink;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
  wire [255:0] _d_channel_arb_io_out_bits_data;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
  wire [6:0]   _d_channel_arb_io_out_bits_user_rsp_intg;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
  wire [6:0]   _d_channel_arb_io_out_bits_user_data_intg;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
  wire         _d_channel_arb_io_out_bits_error;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
  wire         _tl_a_q_io_deq_valid;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:52:22
  wire [2:0]   _tl_a_q_io_deq_bits_opcode;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:52:22
  wire [4:0]   _tl_a_q_io_deq_bits_size;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:52:22
  wire [5:0]   _tl_a_q_io_deq_bits_source;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:52:22
  wire [31:0]  _tl_a_q_io_deq_bits_address;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:52:22
  wire [31:0]  _tl_a_q_io_deq_bits_mask;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:52:22
  wire [255:0] _tl_a_q_io_deq_bits_data;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:52:22
  wire         is_get = _tl_a_q_io_deq_bits_opcode == 3'h4;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:52:22, :78:44
  wire         is_put =
    _tl_a_q_io_deq_bits_opcode == 3'h0 | _tl_a_q_io_deq_bits_opcode == 3'h1;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:52:22, :79:{44,80}, :80:44
  wire         w_q_io_enq_valid = _tl_a_q_io_deq_valid & is_put;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:52:22, :79:80, :86:46
  wire         _read_tx_info_q_io_enq_valid_T = _tl_a_q_io_deq_valid & is_get;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:52:22, :78:44, :108:51
  Queue2_TileLink_A_ChannelBase tl_a_q (	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:52:22
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_ready                (io_tl_a_ready),
    .io_enq_valid                (io_tl_a_valid),
    .io_enq_bits_opcode          (io_tl_a_bits_opcode),
    .io_enq_bits_param           (io_tl_a_bits_param),
    .io_enq_bits_size            (io_tl_a_bits_size),
    .io_enq_bits_source          (io_tl_a_bits_source),
    .io_enq_bits_address         (io_tl_a_bits_address),
    .io_enq_bits_mask            (io_tl_a_bits_mask),
    .io_enq_bits_data            (io_tl_a_bits_data),
    .io_enq_bits_user_rsvd       (io_tl_a_bits_user_rsvd),
    .io_enq_bits_user_instr_type (io_tl_a_bits_user_instr_type),
    .io_enq_bits_user_cmd_intg   (io_tl_a_bits_user_cmd_intg),
    .io_enq_bits_user_data_intg  (io_tl_a_bits_user_data_intg),
    .io_deq_ready
      (is_get & io_axi_read_addr_ready & _read_tx_info_q_io_enq_ready | is_put
       & _aw_q_io_enq_ready & _w_q_io_enq_ready & _write_tx_info_q_io_enq_ready),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:74:30, :75:31, :78:44, :79:80, :85:20, :98:19, :117:42, :118:{37,57}, :119:{36,50,61}
    .io_deq_valid                (_tl_a_q_io_deq_valid),
    .io_deq_bits_opcode          (_tl_a_q_io_deq_bits_opcode),
    .io_deq_bits_size            (_tl_a_q_io_deq_bits_size),
    .io_deq_bits_source          (_tl_a_q_io_deq_bits_source),
    .io_deq_bits_address         (_tl_a_q_io_deq_bits_address),
    .io_deq_bits_mask            (_tl_a_q_io_deq_bits_mask),
    .io_deq_bits_data            (_tl_a_q_io_deq_bits_data)
  );	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:52:22
  CoralNPURRArbiter d_channel_arb (	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
    .clock                       (clock),
    .reset                       (reset),
    .io_in_0_ready               (_d_channel_arb_io_in_0_ready),
    .io_in_0_valid               (io_axi_read_data_valid & _read_tx_info_q_io_deq_valid),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:74:30, :156:49
    .io_in_0_bits_opcode         (_read_response_intg_io_d_o_opcode),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
    .io_in_0_bits_param          (_read_response_intg_io_d_o_param),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
    .io_in_0_bits_size           (_read_response_intg_io_d_o_size),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
    .io_in_0_bits_source         (_read_response_intg_io_d_o_source),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
    .io_in_0_bits_sink           (_read_response_intg_io_d_o_sink),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
    .io_in_0_bits_data           (_read_response_intg_io_d_o_data),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
    .io_in_0_bits_user_rsp_intg  (_read_response_intg_io_d_o_user_rsp_intg),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
    .io_in_0_bits_user_data_intg (_read_response_intg_io_d_o_user_data_intg),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
    .io_in_0_bits_error          (_read_response_intg_io_d_o_error),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
    .io_in_1_ready               (_d_channel_arb_io_in_1_ready),
    .io_in_1_valid
      (io_axi_write_resp_valid & _write_tx_info_q_io_deq_valid),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:75:31, :172:51
    .io_in_1_bits_opcode         (_write_response_intg_io_d_o_opcode),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
    .io_in_1_bits_param          (_write_response_intg_io_d_o_param),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
    .io_in_1_bits_size           (_write_response_intg_io_d_o_size),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
    .io_in_1_bits_source         (_write_response_intg_io_d_o_source),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
    .io_in_1_bits_sink           (_write_response_intg_io_d_o_sink),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
    .io_in_1_bits_data           (_write_response_intg_io_d_o_data),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
    .io_in_1_bits_user_rsp_intg  (_write_response_intg_io_d_o_user_rsp_intg),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
    .io_in_1_bits_user_data_intg (_write_response_intg_io_d_o_user_data_intg),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
    .io_in_1_bits_error          (_write_response_intg_io_d_o_error),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
    .io_out_ready                (_io_tl_d_q_io_enq_ready),	// src/main/scala/chisel3/util/Queue.scala:200:21
    .io_out_valid                (_d_channel_arb_io_out_valid),
    .io_out_bits_opcode          (_d_channel_arb_io_out_bits_opcode),
    .io_out_bits_param           (_d_channel_arb_io_out_bits_param),
    .io_out_bits_size            (_d_channel_arb_io_out_bits_size),
    .io_out_bits_source          (_d_channel_arb_io_out_bits_source),
    .io_out_bits_sink            (_d_channel_arb_io_out_bits_sink),
    .io_out_bits_data            (_d_channel_arb_io_out_bits_data),
    .io_out_bits_user_rsp_intg   (_d_channel_arb_io_out_bits_user_rsp_intg),
    .io_out_bits_user_data_intg  (_d_channel_arb_io_out_bits_user_data_intg),
    .io_out_bits_error           (_d_channel_arb_io_out_bits_error)
  );	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
  Queue2_TileLink_D_ChannelBase io_tl_d_q (	// src/main/scala/chisel3/util/Queue.scala:200:21
    .clock                      (clock),
    .reset                      (reset),
    .io_enq_ready               (_io_tl_d_q_io_enq_ready),
    .io_enq_valid               (_d_channel_arb_io_out_valid),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
    .io_enq_bits_opcode         (_d_channel_arb_io_out_bits_opcode),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
    .io_enq_bits_param          (_d_channel_arb_io_out_bits_param),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
    .io_enq_bits_size           (_d_channel_arb_io_out_bits_size),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
    .io_enq_bits_source         (_d_channel_arb_io_out_bits_source),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
    .io_enq_bits_sink           (_d_channel_arb_io_out_bits_sink),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
    .io_enq_bits_data           (_d_channel_arb_io_out_bits_data),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
    .io_enq_bits_user_rsp_intg  (_d_channel_arb_io_out_bits_user_rsp_intg),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
    .io_enq_bits_user_data_intg (_d_channel_arb_io_out_bits_user_data_intg),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
    .io_enq_bits_error          (_d_channel_arb_io_out_bits_error),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29
    .io_deq_ready               (io_tl_d_ready),
    .io_deq_valid               (io_tl_d_valid),
    .io_deq_bits_opcode         (io_tl_d_bits_opcode),
    .io_deq_bits_param          (io_tl_d_bits_param),
    .io_deq_bits_size           (io_tl_d_bits_size),
    .io_deq_bits_source         (io_tl_d_bits_source),
    .io_deq_bits_sink           (io_tl_d_bits_sink),
    .io_deq_bits_data           (io_tl_d_bits_data),
    .io_deq_bits_user_rsp_intg  (io_tl_d_bits_user_rsp_intg),
    .io_deq_bits_user_data_intg (io_tl_d_bits_user_data_intg),
    .io_deq_bits_error          (io_tl_d_bits_error)
  );	// src/main/scala/chisel3/util/Queue.scala:200:21
  Queue2_TxInfo read_tx_info_q (	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:74:30
    .clock            (clock),
    .reset            (reset),
    .io_enq_ready     (_read_tx_info_q_io_enq_ready),
    .io_enq_valid     (_read_tx_info_q_io_enq_valid_T & io_axi_read_addr_ready),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:108:51, :132:66
    .io_deq_ready     (io_axi_read_data_valid & _d_channel_arb_io_in_0_ready),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29, :179:57
    .io_deq_valid     (_read_tx_info_q_io_deq_valid),
    .io_deq_bits_size (_read_tx_info_q_io_deq_bits_size)
  );	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:74:30
  Queue2_TxInfo write_tx_info_q (	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:75:31
    .clock            (clock),
    .reset            (reset),
    .io_enq_ready     (_write_tx_info_q_io_enq_ready),
    .io_enq_valid     (w_q_io_enq_valid & _aw_q_io_enq_ready & _w_q_io_enq_ready),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:85:20, :86:46, :98:19, :135:{67,88}
    .io_deq_ready     (_d_channel_arb_io_in_1_ready & io_axi_write_resp_valid),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:57:29, :182:64
    .io_deq_valid     (_write_tx_info_q_io_deq_valid),
    .io_deq_bits_size (_write_tx_info_q_io_deq_bits_size)
  );	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:75:31
  Queue1_AxiAddress aw_q (	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:85:20
    .clock             (clock),
    .reset             (reset),
    .io_enq_ready      (_aw_q_io_enq_ready),
    .io_enq_valid      (w_q_io_enq_valid),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:86:46
    .io_enq_bits_addr  (_tl_a_q_io_deq_bits_address),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:52:22
    .io_enq_bits_id    (_tl_a_q_io_deq_bits_source),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:52:22
    .io_enq_bits_size  (_tl_a_q_io_deq_bits_size[2:0]),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:52:22, :90:25
    .io_deq_ready      (io_axi_write_addr_ready),
    .io_deq_valid      (io_axi_write_addr_valid),
    .io_deq_bits_addr  (io_axi_write_addr_bits_addr),
    .io_deq_bits_prot  (io_axi_write_addr_bits_prot),
    .io_deq_bits_id    (io_axi_write_addr_bits_id),
    .io_deq_bits_len   (io_axi_write_addr_bits_len),
    .io_deq_bits_size  (io_axi_write_addr_bits_size),
    .io_deq_bits_burst (io_axi_write_addr_bits_burst)
  );	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:85:20
  Queue1_AxiWriteData w_q (	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:98:19
    .clock            (clock),
    .reset            (reset),
    .io_enq_ready     (_w_q_io_enq_ready),
    .io_enq_valid     (w_q_io_enq_valid),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:86:46
    .io_enq_bits_data (_tl_a_q_io_deq_bits_data),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:52:22
    .io_enq_bits_strb (_tl_a_q_io_deq_bits_mask),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:52:22
    .io_deq_ready     (io_axi_write_data_ready),
    .io_deq_valid     (io_axi_write_data_valid),
    .io_deq_bits_data (io_axi_write_data_bits_data),
    .io_deq_bits_last (io_axi_write_data_bits_last),
    .io_deq_bits_strb (io_axi_write_data_bits_strb)
  );	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:98:19
  ResponseIntegrityGen_32 read_response_intg (	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
    .io_d_i_opcode         (3'h1),
    .io_d_i_param          (3'h0),
    .io_d_i_size           (_read_tx_info_q_io_deq_bits_size),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:74:30
    .io_d_i_source         (io_axi_read_data_bits_id),
    .io_d_i_sink           (1'h0),
    .io_d_i_data           (io_axi_read_data_bits_data),
    .io_d_i_user_rsp_intg  (7'h0),
    .io_d_i_user_data_intg (7'h0),
    .io_d_i_error          (|io_axi_read_data_bits_resp),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:151:53
    .io_d_o_opcode         (_read_response_intg_io_d_o_opcode),
    .io_d_o_param          (_read_response_intg_io_d_o_param),
    .io_d_o_size           (_read_response_intg_io_d_o_size),
    .io_d_o_source         (_read_response_intg_io_d_o_source),
    .io_d_o_sink           (_read_response_intg_io_d_o_sink),
    .io_d_o_data           (_read_response_intg_io_d_o_data),
    .io_d_o_user_rsp_intg  (_read_response_intg_io_d_o_user_rsp_intg),
    .io_d_o_user_data_intg (_read_response_intg_io_d_o_user_data_intg),
    .io_d_o_error          (_read_response_intg_io_d_o_error)
  );	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:143:34
  ResponseIntegrityGen_32 write_response_intg (	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
    .io_d_i_opcode         (3'h0),
    .io_d_i_param          (3'h0),
    .io_d_i_size           (_write_tx_info_q_io_deq_bits_size),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:75:31
    .io_d_i_source         (io_axi_write_resp_bits_id),
    .io_d_i_sink           (1'h0),
    .io_d_i_data           (256'h0),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:166:23
    .io_d_i_user_rsp_intg  (7'h0),
    .io_d_i_user_data_intg (7'h0),
    .io_d_i_error          (|io_axi_write_resp_bits_resp),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:167:55
    .io_d_o_opcode         (_write_response_intg_io_d_o_opcode),
    .io_d_o_param          (_write_response_intg_io_d_o_param),
    .io_d_o_size           (_write_response_intg_io_d_o_size),
    .io_d_o_source         (_write_response_intg_io_d_o_source),
    .io_d_o_sink           (_write_response_intg_io_d_o_sink),
    .io_d_o_data           (_write_response_intg_io_d_o_data),
    .io_d_o_user_rsp_intg  (_write_response_intg_io_d_o_user_rsp_intg),
    .io_d_o_user_data_intg (_write_response_intg_io_d_o_user_data_intg),
    .io_d_o_error          (_write_response_intg_io_d_o_error)
  );	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:159:35
  assign io_axi_write_addr_bits_lock = 1'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7
  assign io_axi_write_addr_bits_cache = 4'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7, :94:26
  assign io_axi_write_addr_bits_qos = 4'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7, :94:26
  assign io_axi_write_addr_bits_region = 4'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7, :94:26
  assign io_axi_write_resp_ready = _d_channel_arb_io_in_1_ready;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7, :57:29
  assign io_axi_read_addr_valid =
    _read_tx_info_q_io_enq_valid_T & _read_tx_info_q_io_enq_ready;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7, :74:30, :108:{51,61}
  assign io_axi_read_addr_bits_addr = _tl_a_q_io_deq_bits_address;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7, :52:22
  assign io_axi_read_addr_bits_prot = 3'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7
  assign io_axi_read_addr_bits_id = _tl_a_q_io_deq_bits_source;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7, :52:22
  assign io_axi_read_addr_bits_len = 8'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7, :89:24
  assign io_axi_read_addr_bits_size = _tl_a_q_io_deq_bits_size[2:0];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7, :52:22, :90:25
  assign io_axi_read_addr_bits_burst = 2'h1;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7
  assign io_axi_read_addr_bits_lock = 1'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7
  assign io_axi_read_addr_bits_cache = 4'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7, :94:26
  assign io_axi_read_addr_bits_qos = 4'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7, :94:26
  assign io_axi_read_addr_bits_region = 4'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7, :94:26
  assign io_axi_read_data_ready = _d_channel_arb_io_in_0_ready;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TLUL2Axi.scala:35:7, :57:29
endmodule


// ----- 8< ----- FILE "verification/cover/layers-TLUL2Axi-Verification_Cover.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
`ifndef layers_TLUL2Axi_Verification_Cover
`define layers_TLUL2Axi_Verification_Cover	// <stdin>:221:5
`endif // layers_TLUL2Axi_Verification_Cover	// <stdin>:221:5

// ----- 8< ----- FILE "verification/assume/layers-TLUL2Axi-Verification_Assume.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
`ifndef layers_TLUL2Axi_Verification_Assume
`define layers_TLUL2Axi_Verification_Assume	// <stdin>:220:5
`endif // layers_TLUL2Axi_Verification_Assume	// <stdin>:220:5

// ----- 8< ----- FILE "verification/assert/layers-TLUL2Axi-Verification_Assert.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
`ifndef layers_TLUL2Axi_Verification_Assert
`define layers_TLUL2Axi_Verification_Assert	// <stdin>:219:5
`endif // layers_TLUL2Axi_Verification_Assert	// <stdin>:219:5
